# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  master:
    docker:
     - image: cimg/base:2022.05
    steps:
      - checkout
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Instalar o git ftp
                command: |
                   sudo apt update
                   sudo apt install git-ftp -y
  # Job two with a unique name
  develop:
    docker:
     - image: cimg/base:2022.05
    steps:
      - checkout
      - when:
          condition:
            equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Instalar o git ftp
                command: |
                   sudo apt update
                   sudo apt install git-ftp -y
                   echo $FTP_HOST_BLOG

workflows:
  # Name of workflow
  principal:
    # List of jobs that will run
    jobs:
      - master
      - develop